import * as T from 'three';
import {ranks,cleanCareer,worldTime,settleDay,promote,AWAKE_LIMIT} from './career-state.js';
import {createAvatar} from './avatar.js';
export function setupCareer({root,scene,homeSystem,life,jobs,keys,setNight}){
 let stored;try{stored=JSON.parse(localStorage.getItem('crystal-island-career'))}catch{}const state=cleanCareer(stored);let last=Date.now(),saveElapsed=0,sleepUntil=0,lastNight=null;
 const boss=createAvatar({top:'#374f6b',pants:'#394552',hair:'#806450',skin:'#d9a279',style:'short',backpack:false});boss.avatar.position.set(-15,.86,3);scene.add(boss.avatar);
 const staff=[{name:'Лена',x:-20,z:10},{name:'Тим',x:-14,z:14},{name:'Саша',x:13,z:-3}].map((person,i)=>{const model=createAvatar({top:['#89ad74','#d0a064','#7ca8bf'][i],style:i===0?'waves':'short',gender:i===0?'girl':'boy',backpack:false});model.avatar.position.set(person.x,.86,person.z);scene.add(model.avatar);const c=document.createElement('canvas');c.width=128;c.height=64;const ctx=c.getContext('2d');ctx.font='bold 42px sans-serif';ctx.fillStyle='white';ctx.textAlign='center';ctx.fillText('Zzz',64,48);const zzz=new T.Sprite(new T.SpriteMaterial({map:new T.CanvasTexture(c)}));zzz.position.set(person.x,3.6,person.z);zzz.scale.set(1.5,.75,1);zzz.visible=false;scene.add(zzz);return {...person,model,zzz,sleeping:false,nextNap:Date.now()+45000+i*15000,taskEnd:0,assignment:''}});
 function wake(i){if(state.rank!==ranks.length-1||!staff[i]?.sleeping)return false;const worker=staff[i];worker.sleeping=false;worker.nextNap=Date.now()+90000;worker.taskEnd=worker.assignment?Date.now()+10000:0;worker.model.avatar.rotation.z=0;worker.zzz.visible=false;return true;}
 const menu=document.createElement('button');menu.id='career-menu';menu.textContent='★ Уровень';document.querySelector('.tools').append(menu);
 const bed=document.createElement('button');bed.id='sleep-button';bed.textContent='☾ Поспать';bed.hidden=true;document.querySelector('.tools').append(bed);
 const hud=document.createElement('div');hud.id='career-hud';root.append(hud);
 const overlay=document.createElement('div');overlay.id='sleep-overlay';overlay.hidden=true;overlay.setAttribute('role','status');root.append(overlay);
 const dialog=document.createElement('dialog');dialog.id='career-dialog';dialog.innerHTML='<h2>Начальник Алексей</h2><p id="career-info"></p><div id="career-ranks"></div><p id="career-feedback" role="status"></p><button id="career-close">Продолжить</button>';root.append(dialog);
 function save(){try{localStorage.setItem('crystal-island-career',JSON.stringify(state))}catch{}}
 function render(){dialog.querySelector('#career-info').textContent=`Уровень: ${ranks[state.rank].name}. Зарплата: ${ranks[state.rank].pay} монет за день, в котором ты выполнил смену. День длится 10 минут: 5 минут света и 5 минут ночи. После двух дней без сна — вынужденный сон; на работе за него будет выговор и пропуск ближайшей зарплаты.`;const list=dialog.querySelector('#career-ranks');list.replaceChildren();ranks.forEach((r,i)=>{const row=document.createElement('div');row.className='product-row';const label=document.createElement('div');label.textContent=`${r.name} · ${r.pay}/день`;const btn=document.createElement('button');btn.textContent=i<=state.rank?(i===state.rank?'Твой уровень':'Пройдено'):`${r.cost} монет`;btn.disabled=i!==state.rank+1||life.state.coins<r.cost;btn.onclick=()=>{if(promote(state,life.state)){life.save();save();render();dialog.querySelector('#career-feedback').textContent=`Повышение: ${ranks[state.rank].name}!`}};row.append(label,btn);list.append(row)});
 if(state.rank===ranks.length-1){const label=document.createElement('p');label.textContent='Управление сменой: выбери работу для сотрудников. Они выполнят смену, и зарплата придёт в конце дня.';list.append(label);for(const name of ['Посадить цветы','Испечь хлеб','Собрать скамейки','Доставить покупки']){const b=document.createElement('button');b.textContent=name;b.disabled=state.worked;b.onclick=()=>{state.worked=true;save();render();dialog.querySelector('#career-feedback').textContent=`Сотрудники получили задание: ${name.toLowerCase()}.`};list.append(b)}const title=document.createElement('h3');title.textContent='Твои сотрудники';list.append(title);staff.forEach((worker,i)=>{const row=document.createElement('div');row.className='product-row';const label=document.createElement('span');label.textContent=`${worker.name} · ${worker.sleeping?'Спит на работе':worker.assignment?'Выполняет задание':'Готов к работе'}`;const wakeButton=document.createElement('button');wakeButton.textContent='Разбудить';wakeButton.disabled=!worker.sleeping;wakeButton.dataset.worker=String(i);wakeButton.onclick=()=>{if(wake(i)){render();dialog.querySelector('#career-feedback').textContent=`${worker.name}: уже не сплю, продолжаю работу!`}};row.append(label,wakeButton);list.append(row)})}}
 menu.onclick=()=>{keys.clear();render();dialog.showModal()};dialog.querySelector('#career-close').onclick=()=>{dialog.close();keys.clear()};
 function sleep(forced=false){if(sleepUntil)return;const atWork=!homeSystem.inside&&Boolean(jobs.state.job);if(forced&&atWork){state.warnings++;state.missPay=true;}for(const d of document.querySelectorAll('dialog[open]'))d.close();keys.clear();sleepUntil=Date.now()+6000;overlay.hidden=false;overlay.textContent=forced&&atWork?'Ты уснул на работе. Алексей сделал выговор: ближайшая зарплата пропущена. Отдыхаем…':forced?'Очень устал… Пора немного поспать.':'Уютная кровать… Отдыхаем и набираемся сил.';save();}
 bed.onclick=()=>sleep(false);addEventListener('keydown',e=>{if(sleepUntil){e.preventDefault();e.stopImmediatePropagation()}},true);
 return {state,staff,boss,wake,get blocked(){return dialog.open||Boolean(sleepUntil)},get sleeping(){return Boolean(sleepUntil)},markWorked(){state.worked=true;save()},update(){const now=Date.now();if(state.rank===ranks.length-1&&!worldTime(state,now).night){let changed=false;for(const w of staff){if(!w.sleeping&&now>=w.nextNap){w.sleeping=true;w.taskEnd=0;w.model.avatar.rotation.z=.4;w.zzz.visible=true;changed=true;}if(!w.sleeping&&w.assignment&&now>=w.taskEnd&&w.taskEnd>0){w.assignment='';w.taskEnd=0;state.worked=true;save();changed=true;}}if(changed&&dialog.open)render();}const delta=Math.min(now-last,60000);last=now;const time=worldTime(state,now);if(time.night!==lastNight){lastNight=time.night;if(!time.night)staff.forEach(w=>{w.sleeping=false;w.nextNap=now+45000;w.model.avatar.rotation.z=0;w.zzz.visible=false});setNight(time.night)}const pay=settleDay(state,now);if(pay){life.reward(pay);save()}const dayButton=document.querySelector('#day');dayButton.textContent=`${time.night?'☾ Ночь':'☀ День'} · ${Math.floor(time.left/60000)}:${String(Math.floor(time.left/1000)%60).padStart(2,'0')}`;dayButton.disabled=true;
 if(homeSystem.chosen!==null&&!sleepUntil){state.awake=Math.min(AWAKE_LIMIT,state.awake+delta);if(state.awake>=AWAKE_LIMIT)sleep(true)}if(sleepUntil&&now>=sleepUntil){sleepUntil=0;state.awake=0;overlay.hidden=true;save()}bed.hidden=!homeSystem.inside||!homeSystem.isOwnRoom;hud.hidden=homeSystem.chosen===null;hud.textContent=`${ranks[state.rank].name} · День ${time.day+1} · Бодрость ${Math.round((1-state.awake/AWAKE_LIMIT)*100)}%`;saveElapsed+=delta;if(saveElapsed>5000){saveElapsed=0;save()}
 }};
}
