import * as T from 'three';
import {products,newLife,buy,consume,tickNeeds} from './life-state.js';
import {houses,groves} from './layout.js';
export const stores=[{x:-9,z:10,name:'Продукты',type:'food'},{x:8,z:-8,name:'Уютный дом',type:'furniture'}];
export function setupLife({scene,avatar,homeSystem,keys,root}){
 let saved;try{saved=JSON.parse(localStorage.getItem('crystal-island-life'))}catch{}const state=newLife(saved);let yards={};try{yards=JSON.parse(localStorage.getItem('crystal-island-yards'))||{}}catch{}
 const material=c=>new T.MeshStandardMaterial({color:c,roughness:.82});const wood=material(0xa77850),white=material(0xfff0cd),leaf=material(0x62a475);
 function box(g,w,h,d,m,x,y,z){const o=new T.Mesh(new T.BoxGeometry(w,h,d),m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;g.add(o);return o}
 function ball(g,r,m,x,y,z){const o=new T.Mesh(new T.SphereGeometry(r,10,8),m);o.position.set(x,y,z);g.add(o);return o}
 function label(g,text,x,y,z){const c=document.createElement('canvas');c.width=512;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='#214f54';ctx.fillRect(0,0,512,128);ctx.fillStyle='#fff0c9';ctx.font='bold 52px sans-serif';ctx.textAlign='center';ctx.fillText(text,256,83);const sprite=new T.Sprite(new T.SpriteMaterial({map:new T.CanvasTexture(c)}));sprite.position.set(x,y,z);sprite.scale.set(5,1.25,1);g.add(sprite);}
 stores.forEach(store=>{const g=new T.Group();g.position.set(store.x,0,store.z);g.name=store.type==='food'?'GroceryStore':'FurnitureStore';scene.add(g);box(g,6,.25,4,wood,0,.9,0);box(g,5,1.4,1.2,wood,0,1.6,.7);for(const x of [-2.6,2.6])box(g,.18,3.6,.18,wood,x,2.6,-.6);for(let i=0;i<8;i++)box(g,.75,.2,4,material(i%2?0xffefc9:store.type==='food'?0x77b69a:0xd4a36c),-2.625+i*.75,4.3,0);label(g,store.name,0,4.9,0);
 if(store.type==='food'){for(let i=0;i<12;i++)ball(g,.2,material(i<6?0xe87856:0xefd47a),-1.8+(i%6)*.35,2.5,.5+Math.floor(i/6)*.45);for(let i=0;i<3;i++)box(g,.3,.65,.3,white,.6+i*.4,2.6,.7);}else{for(let y=1.5;y<3.5;y+=.65)box(g,2,.12,.65,wood,0,y,-1);box(g,1.5,.6,.6,material(0x91aaba),1.3,1.3,0);}});
 const yardModels=new Map();
 function yardSettings(i){const v=yards[i]||{};return {flowers:v.flowers!==false,fence:v.fence!==false,bench:Boolean(v.bench)};}
 function buildYard(i){const old=yardModels.get(i);if(old){scene.remove(old);old.traverse(o=>{o.geometry?.dispose()})}const g=new T.Group();g.name='Yard';const h=houses[i],s=yardSettings(i);g.position.set(h.x,0,h.z);scene.add(g);yardModels.set(i,g);
 if(s.fence)for(const side of [-1,1]){for(let j=0;j<6;j++)box(g,.12,1,.13,white,side*3.5,1.35,.5+j*.65);for(const y of [1.1,1.55])box(g,.1,.1,4,wood,side*3.5,y,2.1)}
 if(s.flowers)for(const side of [-1,1]){box(g,1.2,.4,.9,wood,side*2.4,1,3.1);for(let j=0;j<5;j++){const x=side*2.4+Math.sin(j*2)*.4,z=3.1+Math.cos(j*2)*.25;box(g,.035,.6,.035,leaf,x,1.45,z);for(let k=0;k<5;k++)ball(g,.09,material([0xffc86a,0xeaa8c6,0x9cb7e8][i%3]),x+Math.cos(k*1.25)*.1,1.75,z+Math.sin(k*1.25)*.1);}}
 if(s.bench){box(g,1.4,.15,.65,wood,2.35,1.3,5);box(g,1.4,.6,.12,wood,2.35,1.6,4.7);for(const x of [1.85,2.85])box(g,.14,.55,.5,white,x,1,5);}}
 houses.forEach((_,i)=>buildYard(i));
 const hud=document.createElement('div');hud.id='life-hud';root.append(hud);const note=document.createElement('div');note.id='life-note';note.setAttribute('role','status');root.append(note);let noteUntil=0;
 function notify(text){note.textContent=text;noteUntil=performance.now()+4500}
 function save(){try{localStorage.setItem('crystal-island-life',JSON.stringify(state));localStorage.setItem('crystal-island-yards',JSON.stringify(yards));}catch{notify('Пока сохраняем только до закрытия игры.')}}
 const dialog=document.createElement('dialog');dialog.id='life-dialog';dialog.innerHTML='<h2 id="life-title"></h2><div id="life-items"></div><p id="life-balance"></p><button id="life-close">Готово</button>';dialog.setAttribute('aria-labelledby','life-title');root.append(dialog);let mode='bag';
 const bagButton=document.createElement('button');bagButton.id='inventory';bagButton.textContent='▣ Продукты';document.querySelector('.tools').append(bagButton);
 const yardButton=document.createElement('button');yardButton.id='yard-decor';yardButton.textContent='✿ Мой дворик';yardButton.hidden=true;document.querySelector('.tools').append(yardButton);
 const interact=document.createElement('button');interact.id='world-action';interact.hidden=true;root.append(interact);
 function open(which){mode=which;keys.clear();render();dialog.showModal()}
 function render(){dialog.querySelector('#life-title').textContent=mode==='food'?'Продуктовая лавка':mode==='furniture'?'Магазин мебели':mode==='yard'?'Мой дворик':'Мои продукты';const list=dialog.querySelector('#life-items');list.replaceChildren();
 const row=(title,detail,text,fn,disabled=false)=>{const item=document.createElement('div');item.className='product-row';const words=document.createElement('div');words.innerHTML=`<strong>${title}</strong><small>${detail}</small>`;const btn=document.createElement('button');btn.textContent=text;btn.disabled=disabled;btn.onclick=fn;item.append(words,btn);list.append(item)};
 if(mode==='food'||mode==='bag')for(const p of products)row(`${p.icon} ${p.name}`,mode==='food'?`Сытость +${p.hunger} · вода +${p.thirst}`:`В рюкзаке: ${state.bag[p.id]}`,mode==='food'?`${p.price} монет`:p.id==='water'||p.id==='milk'?'Выпить':'Съесть',()=>{const success=mode==='food'?buy(state,p.id):consume(state,p.id);if(success){save();render();notify(mode==='food'?`${p.name} — в рюкзаке`:'Вкусно! Сил стало больше.')}},mode==='food'?state.coins<p.price:!state.bag[p.id]);
 const own=homeSystem.chosen;
 if(mode==='furniture'){const shelf=homeSystem.hasShelf(),bench=own!==null&&yardSettings(own).bench;row('Деревянная полочка','Поставим в твоём доме',shelf?'Уже дома':'15 монет',()=>{if(state.coins<15||homeSystem.hasShelf()||own===null)return;if(homeSystem.addShelf()){state.coins-=15;save();render();notify('Полочка появилась в твоём доме!')}},shelf||state.coins<15||own===null);row('Садовая скамейка','Поставим в твоём дворике',bench?'Уже во дворе':'12 монет',()=>{if(state.coins<12||own===null||yardSettings(own).bench)return;state.coins-=12;yards[own]={...yardSettings(own),bench:true};buildYard(own);save();render();notify('Скамейка ждёт у дома!')},bench||state.coins<12||own===null);}
 if(mode==='yard'&&own!==null){for(const [key,name] of [['flowers','Цветы у крыльца'],['fence','Невысокий заборчик']]){const value=yardSettings(own)[key];row(name,'Только у твоего домика',value?'Убрать':'Добавить',()=>{yards[own]={...yardSettings(own),[key]:!value};buildYard(own);save();render()})}row('Садовая скамейка',yardSettings(own).bench?'Уже стоит у твоего дома':'Продаётся в магазине «Уютный дом»','Понятно',()=>{},true);}
 dialog.querySelector('#life-balance').textContent=`${state.coins} монет · Монеты зарабатываются в центре профессий.`;}
 dialog.querySelector('#life-close').onclick=()=>{dialog.close();keys.clear()};dialog.addEventListener('cancel',()=>keys.clear());bagButton.onclick=()=>open('bag');yardButton.onclick=()=>open('yard');
 function nearAction(){if(homeSystem.inside||homeSystem.chosen===null)return null;const store=stores.find(s=>Math.hypot(avatar.position.x-s.x,avatar.position.z-(s.z+2.7))<4);if(store)return {type:store.type,text:`${store.name} · E`};return null}
 function action(){if(document.querySelector('dialog[open]'))return;const a=nearAction();if(a)open(a.type)}interact.onclick=action;addEventListener('keydown',e=>{if(e.code==='KeyE'&&!e.repeat)action()});
 let elapsed=0;return {state,get open(){return dialog.open},reward(amount){state.coins=Math.min(999999,state.coins+amount);save();notify(`Зарплата за день: +${amount} монет`)},canWalk(x,z){if(stores.some(s=>Math.abs(x-s.x)<3&&Math.abs(z-s.z)<1.4))return false;return !houses.some((h,i)=>{const v=yardSettings(i),dx=x-h.x,dz=z-h.z;return v.fence&&Math.abs(Math.abs(dx)-3.5)<.25&&dz>.1&&dz<4.15||v.flowers&&Math.abs(Math.abs(dx)-2.4)<.8&&Math.abs(dz-3.1)<.7||v.bench&&Math.abs(dx-2.35)<.9&&Math.abs(dz-5)<.55})},update(dt){const active=homeSystem.chosen!==null&&!document.querySelector('dialog[open]');if(active){tickNeeds(state,dt);elapsed+=dt;if(elapsed>10){elapsed=0;save()}}hud.hidden=homeSystem.chosen===null;hud.textContent=`◈ ${state.coins}   ·   Сытость ${Math.ceil(state.hunger)}%   ·   Вода ${Math.ceil(state.thirst)}%`;if(performance.now()>noteUntil)note.textContent='';const a=nearAction();interact.hidden=!active||!a;if(a)interact.textContent=a.text;const h=houses[homeSystem.chosen];yardButton.hidden=!h||homeSystem.inside||Math.hypot(avatar.position.x-h.x,avatar.position.z-h.z)>10;},save};
}
